spring:
  application:
    name: calendarAPI

  datasource:
    # URL para banco em arquivo com auto-server para evitar locks
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # cria/atualiza tabelas automaticamente
    show-sql: true     # mostra SQL no log (útil para debug)

  h2:
    console:
      enabled: true
      path: /h2-console # caminho padrão
      settings:
        web-allow-others: true # permite acesso externo se necessário

jwt.secret.key: ${JWT_SECRET_KEY:defaultSecretKeyForDev}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
    enabled: true
  scalar:
    enabled: true
    path: /scalar

server:
  port: 8080