spring:
  application:
    name: calendarAPI
  profiles:
    active: hmg
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  scalar:
    enabled: true