spring:
  application:
    name: calendarAPI
  datasource:
    url: jdbc:h2:mem:${DB_NAME:calendardb};MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: ${DB_USER:sa}
    password: ${DB_PASSWORD:}
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,beans,env,loggers
        base-path: /actuator
  endpoint:
    health:
      show-details: always  # Para desenvolvimento
      show-components: always

info:
  app:
    name: ${spring.application.name}
    description: API for managing calendar events
    version: 1.0.0-dev
  company:
    name: Ministerio Atos
    website: https://www.ministerioatos.com

jwt:
  secret:
    key: ${JWT_SECRET_KEY:defaultSecretKeyForDev}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
    enabled: true

scalar:
  enabled: true
  path: /scalar

server:
  port: 8081