spring:
  application:
    name: calendarAPI
  profiles:
    active: dev
  data:
    web:
      page-serialization-mode: via_dto
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
    enabled: true
  scalar:
    enabled: true
    path: /scalar
