spring:
  application:
    name: calendarAPI
    description: API para gerenciamento de calendário em ambiente de produção
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none    # executa ações de DDL automaticamente (usar 'validate' ou 'none' em produção)
    show-sql: false     # mostra SQL no log (útil para debug)

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
    enabled: true
  scalar:
    enabled: true
    path: /scalar

server:
  port: 8080